import LegalDocumentPage from '@/components/LegalDocumentPage';

export const metadata = {
  title: 'Privacy Policy — Automate IT Limited',
  description: 'Read the Privacy Policy for the Dynamic School ERP application.',
};

const sections = [
  {
    heading: 'Privacy Policy',
    paragraphs: [
      'This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You. We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.',
    ],
  },
  {
    heading: 'Interpretation and Definitions',
    paragraphs: [
      'Interpretation: The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.',
    ],
    items: [
      'Account means a unique account created for You to access our Service or parts of our Service.',
      'Affiliate means an entity that controls, is controlled by or is under common control with a party, where control means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.',
      'Application refers to Dynamic School Erp, the software program provided by the Company.',
      'Company refers to Dynamic Technosoft Pvt Ltd, B & S Complex, Shankhamul Marga, Kathmandu.',
      'Country refers to Nepal.',
      'Device means any device that can access the Service such as a computer, a cellphone or a digital tablet.',
      'Personal Data is any information that relates to an identified or identifiable individual.',
      'Service refers to the Application.',
      'Service Provider means any natural or legal person who processes the data on behalf of the Company.',
      'Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.',
      'You means the individual accessing or using the Service, or the company or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.',
    ],
  },
  {
    heading: 'Collecting and Using Your Personal Data',
    paragraphs: [
      'Types of Data Collected',
      'Personal Data: While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to, email address, first name and last name, phone number, usage data, image, and other files.',
      'Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device Internet Protocol address, browser type, browser version, GPS location, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers, and other diagnostic data.',
      'When You access the Service by or through a mobile device, We may collect certain information automatically, including but not limited to the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers, and other diagnostic data.',
      'We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.',
    ],
  },
  {
    heading: 'Information Collected while Using the Application',
    paragraphs: [
      'While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission, information regarding your location and pictures and other information from Your Device camera and photo library.',
      'We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company servers and or a Service Provider server, or it may be simply stored on Your device.',
      'You can enable or disable access to this information at any time through Your Device settings.',
    ],
  },
  {
    heading: 'Use of Your Personal Data',
    items: [
      'To provide and maintain our Service, including to monitor the usage of our Service.',
      'To manage Your Account and manage Your registration as a user of the Service.',
      'For the performance of a contract, including the development, compliance, and undertaking of the purchase contract for products, items, or services You have purchased.',
      'To contact You by email, telephone calls, SMS, push notifications, or other equivalent forms of electronic communication.',
      'To provide You with news, special offers, and general information about other goods, services, and events unless You have opted not to receive such information.',
      'To manage Your requests.',
      'For business transfers such as merger, divestiture, restructuring, reorganization, dissolution, or sale or transfer of assets.',
      'To collect GPS location data to trace Salesman User activity via admin users, including background tracking until logout from the Application.',
      'For other purposes such as data analysis, identifying usage trends, determining promotional campaign effectiveness, and improving our Service, products, services, marketing, and Your experience.',
    ],
  },
  {
    heading: 'Sharing of Your Personal Information',
    items: [
      'With Service Providers to monitor and analyze the use of our Service and to contact You.',
      'For business transfers in connection with mergers, sales of Company assets, financing, or acquisition of all or a portion of Our business.',
      'With Affiliates, including Our parent company, subsidiaries, joint venture partners, or companies under common control.',
      'With business partners to offer You certain products, services, or promotions.',
      'With other users when You share personal information or interact in public areas.',
      'With Your consent for any other purpose.',
    ],
  },
  {
    heading: 'Retention, Transfer, and Deletion of Your Personal Data',
    paragraphs: [
      'The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will also retain and use Your Personal Data to the extent necessary to comply with legal obligations, resolve disputes, and enforce our legal agreements and policies.',
      'Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or improve the functionality of Our Service, or when We are legally obligated to retain this data for longer periods.',
      'Your information, including Personal Data, may be transferred to and maintained on computers located outside of Your state, province, country, or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.',
      'The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy.',
      'You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You. You may update, amend, or delete Your information through Your Account, if applicable, or by contacting Us directly.',
    ],
  },
  {
    heading: 'Disclosure of Your Personal Data',
    items: [
      'Business Transactions: If the Company is involved in a merger, acquisition, or asset sale, Your Personal Data may be transferred.',
      'Law enforcement: The Company may disclose Your Personal Data if required to do so by law or in response to valid public authority requests.',
      'Other legal requirements: to comply with legal obligations, protect and defend the rights or property of the Company, prevent wrongdoing, protect user or public safety, and protect against legal liability.',
    ],
  },
  {
    heading: 'Security, Children, and Third-Party Links',
    paragraphs: [
      'The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.',
      'Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If We become aware that We have collected Personal Data from anyone under 13 without verification of parental consent, We take steps to remove that information from Our servers.',
      'Our Service may contain links to other websites that are not operated by Us. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third-party sites or services.',
    ],
  },
  {
    heading: 'Changes to this Privacy Policy',
    paragraphs: [
      'We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.',
      'We will let You know via email and or a prominent notice on Our Service, prior to the change becoming effective, and update the Last updated date at the top of this Privacy Policy.',
      'You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.',
    ],
  },
];

export default function PrivacyPolicyPage() {
  return (
    <LegalDocumentPage
      title="Privacy Policy"
      summary="This policy explains how the Dynamic School ERP application collects, uses, stores, shares, and protects personal information."
      sections={sections}
      contacts={['Automate IT Limited', '09678-221323', 'info@automate.com.bd', 'automate.com.bd']}
    />
  );
}
